from flask import Blueprint
views = Blueprint('views', __name__)

from views.get_list_of_project import *
from views.change_password import *
from views.get_project_specific import *
from views.get_user import *
from views.login import *
from views.index import *
from views.create_user_account import *
from views.create_project import *
from views.logout import *
from views.create_developer import *
from views.assign_developer import *
from views.remove_developer import *
from views.search_user import *
from views.update_project_info import *
from views.update_soft_metrics import *
from views.assign_pm import *
from views.unassign_pm import *
from views.get_all_pm import *
from views.get_unassigned_pm import *
from views.request_evaluation import *
